[tool.ruff]
target-version = "py310"
line-length = 100
src = ["src", "tests", "examples"]
fix = true
show-fixes = true

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
extend-select = ["B", "Q", "I", "UP"]
ignore = [
    "E203",
    "E402",
    "F821",
    "F405",
    "F403",
    "E731",
    "B006",
    "B008"
]

[tool.ruff.lint.pylint]
max-returns = 5
max-args = 25

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.pydocstyle]
convention = "google"