module:
    _target_: src.model.ClassificationRegressionModule
    backbone: resnet18
    num_channels: 3
    num_classes: 5
    learning_rate: 0.001

datamodule:
    _target_: torchgeo.datamodules.QuakeSetDataModule
    root: ./data
    batch_size: 32
    num_workers: 16
    num_prefetch: 2

trainer:
    max_epochs: 50
    precision: 32-true
    gpus: 1
    log_every_n_steps: 5